-- MySQL Script generated by MySQL Workbench
-- 03/16/15 14:16:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bancoscrum
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bancoscrum` ;

-- -----------------------------------------------------
-- Schema bancoscrum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancoscrum` DEFAULT CHARACTER SET latin1 ;
USE `bancoscrum` ;

-- -----------------------------------------------------
-- Table `bancoscrum`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoscrum`.`Usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL,
  `foiExcluido` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `bancoscrum`.`Projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoscrum`.`Projeto` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(30) NOT NULL,
  `descricao` TEXT NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL,
  `foiExcluido` TINYINT(1) NOT NULL,
  `idUsuario` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bancoscrum`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `usuario9_idx` ON `bancoscrum`.`Projeto` (`idUsuario` ASC);


-- -----------------------------------------------------
-- Table `bancoscrum`.`Sprint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoscrum`.`Sprint` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(30) NOT NULL,
  `descricao` TEXT NOT NULL,
  `diasUteis` SMALLINT(2) UNSIGNED NOT NULL,
  `diasCerimonias` SMALLINT(2) UNSIGNED NULL,
  `horasTrabDia` TIME NOT NULL,
  `foco` INT NOT NULL,
  `dataInicio` DATETIME NULL,
  `dataConclusao` DATETIME NULL,
  `status` INT UNSIGNED NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL DEFAULT NULL,
  `foiExcluido` TINYINT(1) NOT NULL DEFAULT 0,
  `idProjeto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `projeto1`
    FOREIGN KEY (`idProjeto`)
    REFERENCES `bancoscrum`.`Projeto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `projeto1_idx` ON `bancoscrum`.`Sprint` (`idProjeto` ASC);


-- -----------------------------------------------------
-- Table `bancoscrum`.`Estoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoscrum`.`Estoria` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(30) NULL,
  `descricao` TEXT NOT NULL,
  `pontosEstimados` SMALLINT(5) UNSIGNED NOT NULL,
  `dataInicio` DATETIME NULL,
  `dataConclusao` DATETIME NULL,
  `status` INT UNSIGNED NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL,
  `foiExcluido` TINYINT(1) NOT NULL,
  `idSprint` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `sprint1`
    FOREIGN KEY (`idSprint`)
    REFERENCES `bancoscrum`.`Sprint` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `sprint1_idx` ON `bancoscrum`.`Estoria` (`idSprint` ASC);


-- -----------------------------------------------------
-- Table `bancoscrum`.`Papel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoscrum`.`Papel` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(30) NOT NULL,
  `descricao` TEXT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL,
  `foiExcluido` TINYINT(1) NOT NULL,
  `idUsuario` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `usuario4`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bancoscrum`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `usuario4_idx` ON `bancoscrum`.`Papel` (`idUsuario` ASC);


-- -----------------------------------------------------
-- Table `bancoscrum`.`Time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoscrum`.`Time` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL,
  `foiExcluido` TINYINT(1) NOT NULL,
  `idUsuario` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `usuario5`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bancoscrum`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `usuario5_idx` ON `bancoscrum`.`Time` (`idUsuario` ASC);


-- -----------------------------------------------------
-- Table `bancoscrum`.`MembroTime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoscrum`.`MembroTime` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dataCriacao` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL,
  `foiExcluido` TINYINT(1) NOT NULL,
  `idPapel` INT UNSIGNED NOT NULL,
  `idTime` INT UNSIGNED NOT NULL,
  `idUsuario` INT UNSIGNED NOT NULL COMMENT 'Usuário pertencente ao time, que desempenha um papel definido por quem cria o time.',
  PRIMARY KEY (`id`),
  CONSTRAINT `papel1`
    FOREIGN KEY (`idPapel`)
    REFERENCES `bancoscrum`.`Papel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `time1`
    FOREIGN KEY (`idTime`)
    REFERENCES `bancoscrum`.`Time` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario6`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bancoscrum`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `papel1_idx` ON `bancoscrum`.`MembroTime` (`idPapel` ASC);

CREATE INDEX `time1_idx` ON `bancoscrum`.`MembroTime` (`idTime` ASC);

CREATE INDEX `usuario6_idx` ON `bancoscrum`.`MembroTime` (`idUsuario` ASC);


-- -----------------------------------------------------
-- Table `bancoscrum`.`Tipotarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoscrum`.`Tipotarefa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(30) NULL,
  `descricao` TEXT NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL,
  `foiExcluido` TINYINT(1) NOT NULL,
  `idUsuario` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `usuario3`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bancoscrum`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `usuario3_idx` ON `bancoscrum`.`Tipotarefa` (`idUsuario` ASC);


-- -----------------------------------------------------
-- Table `bancoscrum`.`Tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoscrum`.`Tarefa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(30) NOT NULL,
  `descricao` TEXT NULL,
  `horasEstimativa` TIME NOT NULL,
  `horasEfetiva` TIME NULL,
  `dataConclusao` DATETIME NULL,
  `obs` VARCHAR(255) NULL,
  `status` INT UNSIGNED NOT NULL,
  `dataInicio` DATETIME NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL,
  `foiExcluido` TINYINT(1) NOT NULL,
  `idEstoria` INT UNSIGNED NOT NULL,
  `idTipotarefa` INT UNSIGNED NOT NULL,
  `idUsuarioPapelTime` INT UNSIGNED NULL COMMENT 'Representa o Usuário que irá executar a tarefa,\ntime em que ele está alocado e pepel atribuido.',
  PRIMARY KEY (`id`),
  CONSTRAINT `estoria`
    FOREIGN KEY (`idEstoria`)
    REFERENCES `bancoscrum`.`Estoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipotarefa1`
    FOREIGN KEY (`idTipotarefa`)
    REFERENCES `bancoscrum`.`Tipotarefa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuarioPapelTime1`
    FOREIGN KEY (`idUsuarioPapelTime`)
    REFERENCES `bancoscrum`.`MembroTime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `estoria_idx` ON `bancoscrum`.`Tarefa` (`idEstoria` ASC);

CREATE INDEX `tipotarefa1_idx` ON `bancoscrum`.`Tarefa` (`idTipotarefa` ASC);

CREATE INDEX `usuarioPapelTime1_idx` ON `bancoscrum`.`Tarefa` (`idUsuarioPapelTime` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
