-- MySQL Script generated by MySQL Workbench
-- 10/09/14 17:41:13
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bancoscrum
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bancoscrum` ;
CREATE SCHEMA IF NOT EXISTS `bancoscrum` DEFAULT CHARACTER SET latin1 ;
USE `bancoscrum` ;

-- -----------------------------------------------------
-- Table `bancoscrum`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoscrum`.`usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL,
  `foiExcluido` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `bancoscrum`.`projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoscrum`.`projeto` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL,
  `foiExcluido` TINYINT(1) NOT NULL,
  `id_usuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bancoscrum`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `usuario9_idx` ON `bancoscrum`.`projeto` (`id_usuario` ASC);


-- -----------------------------------------------------
-- Table `bancoscrum`.`sprint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoscrum`.`sprint` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` TEXT NOT NULL,
  `diasUteis` SMALLINT(2) UNSIGNED NOT NULL,
  `diasCerimonias` SMALLINT(2) UNSIGNED NULL,
  `horasTrabDia` TIME NOT NULL,
  `foco` INT NOT NULL,
  `dataInicio` DATETIME NULL,
  `dataConclusao` DATETIME NULL,
  `status` INT UNSIGNED NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL DEFAULT NULL,
  `foiExcluido` TINYINT(1) NOT NULL DEFAULT 0,
  `id_projeto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `projeto1`
    FOREIGN KEY (`id_projeto`)
    REFERENCES `bancoscrum`.`projeto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `projeto1_idx` ON `bancoscrum`.`sprint` (`id_projeto` ASC);


-- -----------------------------------------------------
-- Table `bancoscrum`.`estoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoscrum`.`estoria` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `ptsEstimados` SMALLINT(5) UNSIGNED NOT NULL,
  `dataInicio` DATETIME NULL,
  `dataConclusao` DATETIME NULL,
  `status` INT UNSIGNED NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL,
  `foiExcluido` TINYINT(1) NOT NULL,
  `id_sprint` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `sprint1`
    FOREIGN KEY (`id_sprint`)
    REFERENCES `bancoscrum`.`sprint` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `sprint1_idx` ON `bancoscrum`.`estoria` (`id_sprint` ASC);


-- -----------------------------------------------------
-- Table `bancoscrum`.`papel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoscrum`.`papel` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL,
  `foiExcluido` TINYINT(1) NOT NULL,
  `id_usuario` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `usuario4`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bancoscrum`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `usuario4_idx` ON `bancoscrum`.`papel` (`id_usuario` ASC);


-- -----------------------------------------------------
-- Table `bancoscrum`.`time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoscrum`.`time` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL,
  `foiExcluido` TINYINT(1) NOT NULL,
  `id_usuario` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `usuario5`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bancoscrum`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `usuario5_idx` ON `bancoscrum`.`time` (`id_usuario` ASC);


-- -----------------------------------------------------
-- Table `bancoscrum`.`usuarioPapelTime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoscrum`.`usuarioPapelTime` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dataCriacao` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL,
  `foiExcluido` TINYINT(1) NOT NULL,
  `id_papel` INT UNSIGNED NOT NULL,
  `id_time` INT UNSIGNED NOT NULL,
  `id_usuario` INT UNSIGNED NOT NULL COMMENT 'Usuário pertencente ao time, que desempenha um papel definido por quem cria o time.',
  PRIMARY KEY (`id`),
  CONSTRAINT `papel1`
    FOREIGN KEY (`id_papel`)
    REFERENCES `bancoscrum`.`papel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `time1`
    FOREIGN KEY (`id_time`)
    REFERENCES `bancoscrum`.`time` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario6`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bancoscrum`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `papel1_idx` ON `bancoscrum`.`usuarioPapelTime` (`id_papel` ASC);

CREATE INDEX `time1_idx` ON `bancoscrum`.`usuarioPapelTime` (`id_time` ASC);

CREATE INDEX `usuario6_idx` ON `bancoscrum`.`usuarioPapelTime` (`id_usuario` ASC);


-- -----------------------------------------------------
-- Table `bancoscrum`.`tipotarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoscrum`.`tipotarefa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL,
  `foiExcluido` TINYINT(1) NOT NULL,
  `id_usuario` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `usuario3`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bancoscrum`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `usuario3_idx` ON `bancoscrum`.`tipotarefa` (`id_usuario` ASC);


-- -----------------------------------------------------
-- Table `bancoscrum`.`tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoscrum`.`tarefa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `horasEstimativa` TIME NOT NULL,
  `horasEfetiva` TIME NULL,
  `dataConclusao` DATETIME NULL,
  `obs` VARCHAR(255) NULL,
  `status` INT UNSIGNED NOT NULL,
  `dataInicio` DATETIME NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL,
  `foiExcluido` TINYINT(1) NOT NULL,
  `id_estoria` INT UNSIGNED NOT NULL,
  `id_tipotarefa` INT UNSIGNED NOT NULL,
  `id_usuarioPapelTime` INT UNSIGNED NULL COMMENT 'Representa o Usuário que irá executar a taref' /* comment truncated */ /*,
time em que ele está alocado e pepel atribuido.*/,
  PRIMARY KEY (`id`),
  CONSTRAINT `estoria`
    FOREIGN KEY (`id_estoria`)
    REFERENCES `bancoscrum`.`estoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipotarefa1`
    FOREIGN KEY (`id_tipotarefa`)
    REFERENCES `bancoscrum`.`tipotarefa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuarioPapelTime1`
    FOREIGN KEY (`id_usuarioPapelTime`)
    REFERENCES `bancoscrum`.`usuarioPapelTime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `estoria_idx` ON `bancoscrum`.`tarefa` (`id_estoria` ASC);

CREATE INDEX `tipotarefa1_idx` ON `bancoscrum`.`tarefa` (`id_tipotarefa` ASC);

CREATE INDEX `usuarioPapelTime1_idx` ON `bancoscrum`.`tarefa` (`id_usuarioPapelTime` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
